pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('login') {
                    sh './gradlew clean build'
                }
            }
        }

        stage('Test') {
            steps {
                dir('login') {
                    sh './gradlew test'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('login') {
                    sh 'docker build -t dipic/login-image .'
                }
            }
        }

        stage('Docker Push') {
            steps {
                dir('login') {
                    sh 'docker push dipic/login-image'
                }
            }
        }

    }

    post {
        success {
            echo 'Job successed'
        }
        failure {
            echo 'Job failed'
        }
    }

}
