def fileExists(filename) {
    def file = new File(filename)
    file.exists()
}

pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
                sh 'rm -rf BE-login'
                sh 'git clone https://github.com/DKU-CloudComputing/BE-login.git'
            }
        }

        stage('Build') {
            steps {
                script {
                    sh 'pwd'
                    sh 'ls'
                    sh 'chmod +x BE-login/login/gradlew'
                    sh 'BE-login/login/gradlew init'
                    sh 'BE-login/login/gradlew clean build'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh 'BE-login/login/gradlew test'
                }
            }
        }

        stage('Docker Build') {
            steps {
                script {
                    sh 'docker --version'
                    sh 'docker build -t dipic/login-image BE-login/login/'
                }
            }
        }

        stage('Docker Push') {
            steps {
                script {
                    sh 'docker push dipic/login-image'
                }
            }
        }

        stage('Kubernetes Deploy') {
            steps {
                script {
                    sh 'kubectl apply -f BE-login/login/deployment.yaml'
                    sh 'kubectl apply -f BE-login/login/service.yaml'
                }
            }
        }
    }

    post {
        success {
            echo 'Build successful! Deploying...'
        }
        failure {
            echo 'Build failed! Not deploying.'
        }
    }
}
