apiVersion: v1
kind: Service
metadata:
  name: springboot-service
  namespace: springboot
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: springboot
      port: 8080
      targetPort: 8080
  selector:
    app: springboot