apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-service
spec:
  selector:
    app: springboot-k8s
  ports:
    - protocol: "TCP"
      port: 8080  # The port that the container is running on in the cluster
      targetPort: 8080  # The port exposed by the service
  type: LoadBalancer